### ISSUE TITLE
Feature request: Make it easier to integrate as dependency

### ISSUE THREAD

**Issue by gitandeee** [prophesee-ai/openeb#95]
Hi,

I would appreciate it, if the package would be made easier to integrate from source as a dependency in cmake to be able to link it statically, rather than depending on (preinstalled) shared libraries. This also would make debugging simpler.

When integrating this package as a dependency it is quite difficult to build. E.g. using it with CPMAddPackage (https://github.com/cpm-cmake/CPM.cmake) or conan (through a conanfile.py) is currently almost impossible without modifying the shipped CMakeLists.txt files , because e.g. CMAKE_SOURCE_DIR is defined instead CMAKE_CURRENT_SOURCE_DIR. This screws up the whole compilation.

Thank you in advance!

**Comment by lbristiel-psee** [comment]
Hello @gitandeee ,

thanks for the feedback! Indeed, the enhancements/fixes you suggest could make it easie to integrate OpenEB in other projects. We need to analyse their complexity on our side. Could you possibly provide a bit more details on what you are trying to achieve and the limitations you mentioned? You could also submit a PR so that we can see the changes you have in mind as this would help us evaluate what we should/could do. 

Thx,
Laurent for Prophesee
